[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "llama-index-workflows"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "llama-index-instrumentation>=0.1.0",
    "pydantic>=2.11.5",
]

[dependency-groups]
dev = ["pytest>=8.4.0", "pytest-asyncio>=1.0.0", "pytest-cov>=6.1.1"]

[tool.hatch.build.targets.wheel]
packages = ["src/workflows"]
